[project]
name = "SITCON-Camp-Sample-Backend"
version = "0.1.0"
description = "This is a sample backend for SITCON Camp 2025 deploy."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.116.0",
]

